### ISSUE TITLE
Execute JS before screenshots taken

### ISSUE THREAD

**Issue by thomasjbradley** [thomasjbradley/markbot#110]
Add the ability to execute JS before the screenshots are taken, so see how the visuals react.

Maybe `screenshots` could optionally be an array of objects:

```yml
screenshots:
  - path: 'index.html'
    sizes:
      - width: 320
        before: |
          $('.btn').click();
```
