### ISSUE TITLE
Allow warnings in has/Not & search/Not

### ISSUE THREAD

**Issue by thomasjbradley** [thomasjbradley/markbot#137]
Possibly expand the syntax to trigger a warning type, maybe something like:

```yaml
has:
  - check: 'h1'
    type: 'warning'
```
