### ISSUE TITLE
Has in HTML should allow a limit

### ISSUE THREAD

**Issue by thomasjbradley** [thomasjbradley/markbot#138]
The primary use-case would be for limiting the amount of times ARIA landmark roles are used, like:

```yml
has:
  - check: 'header[role="banner"]'
    limit: 1
```
