### ISSUE TITLE
MarkbotFile scoping

### ISSUE THREAD

**Issue by thomasjbradley** [thomasjbradley/markbot#168]
This is a complicated problem that I’m not sure needs to be solved, but would be very helpful, especially for large projects like the pattern libraries.

Some kind of scoped MarkbotFiles where certain requirements can be specified against certain files, but different requirements against different files. It’s possible to do this if you know the names of the files ahead of time, but if the filenames are unknown it isn’t possible.

Here’s my initial thought:

```yml
scopes:
  - path: 'patterns/*'
    inherit:
      - html
      - css
    allFiles:
      html:
        outline: false
  
  - path: 'pages/*'
    inherit:
      - html
      - aria-landmarks
```
