### ISSUE TITLE
Common requirements

### ISSUE THREAD

**Issue by thomasjbradley** [thomasjbradley/markbot#33]
It’d be great to be able to provide common requirements for all the HTML or CSS files instead of having to repeat everything.

Maybe an `html_defaults` or `html_common` key in the Markbot file.

**Comment by thomasjbradley** [comment]
I’ve decided on:

```yml
defaults:
  inherit: thomasjbradley-defaults
  html:
    valid: true
    bestPractices: true
  js:
    valid: true
```

`inherit` is something I’m thinking of that would allow me to not have to repeat myself in all my Markbot files. I’d create a default set of defaults that I could inherit from and change.
