### ISSUE TITLE
Document heading stucture testing

### ISSUE THREAD

**Issue by thomasjbradley** [thomasjbradley/markbot#57]
https://github.com/edenspiekermann/outline-audit

**Comment by thomasjbradley** [comment]
```yml
html:
  - path: index.html
    outline: true
```
