### ISSUE TITLE
Git status checking

### ISSUE THREAD

**Issue by thomasjbradley** [thomasjbradley/markbot#58]
- Confirm that there are now outstanding files to be committed.
- Confirm that everything has been synced.

https://www.npmjs.com/package/git-get-status

**Comment by thomasjbradley** [comment]
```yml
git:
  numCommits: 10
  allCommitted: true
  allSynced: true
```
