### ISSUE TITLE
Media query space at bottom not required

### ISSUE THREAD

**Issue by thomasjbradley** [thomasjbradley/markbot#87]
I'd like to force an empty line at the end of media queries like you can at the start of media queries:

```css
@media print {

  a {
    color: red;
  }
            /* <----- Force this empty line here */
}
```

Stylelint doesn’t seem to be capable of doing it.
